### ISSUE TITLE
PXD-2429 ⁃ Getting 403 errors, despite having access

### ISSUE THREAD

**Issue by bwalsh** [uc-cdis/sheepdog#219]
Hello,

Thanks for a great project.  I'm exploring the gen3 suite as part of the anvil project.
I was able to get the docker containers up quickly.  Created a program and project.  Added my user to the project.  However, I do not seem to be able to create `experiments` ?

-b

![image](https://user-images.githubusercontent.com/47808/49399420-0c16ab00-f6f6-11e8-9dc6-d603d1aaad58.png)

```
PUT http://localhost/api/v0/submission/test/test/

{
  "type": "experiment",
  "data_description": "test",
  "projects": [
    {
      "submitter_id": "XXX"
    }
  ],
  "submitter_id": "XXX"
}

```

```
sheepdog-service     | [2018-12-03 20:13:30,571] ERROR in api: [403] - You don't have access to this resource: User brian@bwalsh.com doesn't have create or update access in test
sheepdog-service     | Traceback (most recent call last):
sheepdog-service     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
sheepdog-service     |     rv = self.dispatch_request()
sheepdog-service     |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
sheepdog-service     |     return self.view_functions[rule.endpoint](**req.view_args)
sheepdog-service     |   File "/sheepdog/sheepdog/utils/__init__.py", line 170, in check_and_call
sheepdog-service     |     return func(program, project, *args, **kwargs)
sheepdog-service     |   File "/sheepdog/sheepdog/auth/__init__.py", line 120, in authorize_and_call
sheepdog-service     |     current_user.username, required_roles, project
sheepdog-service     | AuthZError: [403] - You don't have access to this resource: User brian@bwalsh.com doesn't have create or update access in test

```

**Comment by paulineribeyre** [comment]
Hello,
`PUT http://localhost/api/v0/submission/test/test/` tries to submit to program `test`, project `test`. From your screenshot, it looks like the program you created is called `DEV`, so `PUT http://localhost/api/v0/submission/DEV/test/` might be what you are looking for.

**Comment by bwalsh** [comment]
@paulineribeyre  
Thanks so much for the quick response.

* The DEV and project1 entries were there by default in [compose services](https://github.com/uc-cdis/compose-services/blob/master/apis_configs/user.yaml#L11-L14).  
  * I've removed them and verified the db entries


```
fence_db=# select * from user_refresh_token ;
                 jti                  | userid |  expires
--------------------------------------+--------+------------
 XXXX  |      1 | 1546456597

fence_db=# select * from "User" ;
 id |     username     | id_from_idp | display_name | phone_number |      email       | idp_id | google_proxy_group_id | department_id | active | is_admin
----+------------------+-------------+--------------+--------------+------------------+--------+-----------------------+---------------+--------+----------
  1 | brian@bwalsh.com |             |              |              | brian@bwalsh.com |        |                       |               |        | t
  2 | cdis             |             |              |              | cdis             |        |                       |               |        | t

metadata_db=# select * from node_project ;
            created            | acl | _sysan |                                                         _props                                                         |               node_id
-------------------------------+-----+--------+------------------------------------------------------------------------------------------------------------------------+--------------------------------------
 2018-12-03 19:36:05.369296+00 | {}  | {}     | {"code": "test", "name": "test", "state": "open", "availability_type": "Open", "dbgap_accession_number": "test-dbgap"} | a77f549b-c74b-563e-80bb-570b5a4dde88
(1 row)

metadata_db=# select * from node_program ;
            created            | acl | _sysan |                          _props                          |               node_id
-------------------------------+-----+--------+----------------------------------------------------------+--------------------------------------
 2018-12-03 19:28:55.134005+00 | {}  | {}     | {"name": "test", "dbgap_accession_number": "test-dbgap"} | 98ae2403-b7db-5815-b8be-3eec031c997c
(1 row)

metadata_db=# select * from edge_projectmemberofprogram ;
            created            | acl | _sysan | _props |                src_id                |                dst_id
-------------------------------+-----+--------+--------+--------------------------------------+--------------------------------------
 2018-12-03 19:36:05.369296+00 | {}  | {}     | {}     | a77f549b-c74b-563e-80bb-570b5a4dde88 | 98ae2403-b7db-5815-b8be-3eec031c997c
(1 row)
```
![image](https://user-images.githubusercontent.com/47808/49404495-73d3f280-f704-11e8-9159-aaac4a6dc93f.png)

**Comment by philloooo** [comment]
the dbgap_accession_number is used to check against the project auth_id. And that's supposed to be unique so you wouldn't want to set program project to use the same string. we will rename this field to something that makes more sense. For now you can update your node_project dbgap_accession_number to `test` and that should work

**Comment by bwalsh** [comment]
Thank you.  I manually altered the project's dbgap_accession_number, then resubmitted using the project's uuid.  It worked!  Thanks again.   

```
update node_project set _props = jsonb_set(_props, '{dbgap_accession_number}', '"test"') where node_id = 'a77f549b-c74b-563e-80bb-570b5a4dde88' ;
```

```
{
  "type": "experiment",
  "data_description": "test",
  "projects": [
    {
      "id": "a77f549b-c74b-563e-80bb-570b5a4dde88",
      "submitter_id": "XXX"
    }
  ],
  "submitter_id": "XXX"
}
```
